### PR TITLE
Update webhook module to allow publication

### PR DESCRIPTION
**Pull request by csaroff**
Publishers can create webhooks and supply HMAC authentication to their subscribers.

### CODE REVIEW

**Comment by jsdelfino** [comment]
Hey @csaroff could you resubmit this as a single commit maybe? It's a little difficult for me to review the latest state as changes are distributed in different commits. Thanks!

**Comment by csaroff** [comment]
Squashed.  Do you prefer all PR's submitted as one commit?

**Comment by jsdelfino** [comment]
I'm going to open an issue to discuss Webhook authentication, as it'll be easier for others to follow (and I'm also not able to figure out how to respond to your comment response here...)

**Comment by csaroff** [comment]
This update resolves issue #261 by allowing abacus-webhook to remain entirely agnostic to a module consumer's use of authentication.  It uses [request](https://github.com/request/request) instead of abacus-request because abacus-request lacks the [request.defaults](https://github.com/request/request#requestdefaultsoptions) method(pending a resolution to issue #272).

**Comment by betafood** [comment]
Hey @csaroff, everything looks good from a quick look through it. I do have one question. I do understand and agree with not using abacus-request due to the current lack of the defaults function, but the question I have is based on the options passed here:
```
const request = require('request').defaults({ method: 'post' });
```
I'm wondering. Wouldn't it also work with abacus request if you replace this line:
```
const trequest = throttle(request, options.concurrency || 5);
```
to say
```
const trequest = throttle(request.post, options.concurrency || 5);
```
and not worry about setting a defaults?

**Comment by csaroff** [comment]
@betafood Yes, it will work, but it forces the API consumer to use http post.  While this is the standard http verb used in webhooks, I was hoping to give the api consumer the ability to change the http verb if they wanted to.  I think that the long term solution is to make abacus-request more extensible, but in the meantime, do you have any wisdom here?  Should I just update the module to be more strict and use abacus-request?

**Comment by betafood** [comment]
@csaroff I think I agree with your reasoning here. I only brought it up since I only saw the post passed into the options. The idea is that a consumer would be able to pass in some sort of options whether it's just the http verb to the request defaults as well, correct?

I personally don't see a problem with using request for now until abacus-request has its own defaults function implemented (as you said would be the long term solution here). The only thing that pops out to me at the moment is losing debugging with an variable like "abacus-*" or "e-abacus-*"

**Comment by csaroff** [comment]
> The idea is that a consumer would be able to pass in some sort of options whether it's just the http verb to the request defaults as well, correct?
Correct

> The only thing that pops out to me at the moment is losing debugging with an variable like "abacus-" or "e-abacus-"
That's a good point.  I'm happy to update to abacus-request.  I don't have a strong opinion on extensibility vs. debugging advantages here.  @KRuelY Do you have any insight?

**Comment by KRuelY** [comment]
> That's a good point. I'm happy to update to abacus-request. I don't have a strong opinion on extensibility vs. debugging advantages here.

I do not have a strong opinion too, but if I have to say something:

The abacus-request debug is probably the most useful debug. It is the only debug set (Other than e-*) in the integration test that I have because it tells us the target, statusCode, body, options, etc.

With abacus-request's debug, we do not have to write the debug code block(Something like 'making request to this endpoint with body x' and 'the result of the call is x') each time we want to make a request call in the app/module that we're working on. Which could be convenient for the webhook module in case you want to see the result of the calls.

We probably want both extensibility and the convenience for debugging, so it is probably better to update abacus-request?

**Comment by csaroff** [comment]
@KRuelY Based on what you're saying, I gather that a PR for #272 is a prerequisite for this PR.  Thanks for the explanation.

**Comment by maximilien** [comment]
@KRuelY and @csaroff any updates on this PR?

**Pull request closed without merging**
