### PR TITLE
Stores resource definitions in database.

### PR DESCRIPTION
**Pull request by rajkiranrbala**
Updated the provisioning stub read resources from the database. Also if a resource is not present, the resources directory is checked to see if a resource is present. This helps in loading the existing resources

### CODE REVIEW

**Comment by jsdelfino** [comment]
Thanks for this nice contribution!

There are some minor issues in the code, but they are only minor, so I'm going to merge the pull request and add some comments to the commit, hoping you can address the issue in a follow up pull request.

I'm also only picking up the first commit from the request as the second one seems to target another branch from your fork (looks like they both contain the same changes).

**Comment by jsdelfino** [comment]
@rajkiranrbala Actually, I'm not able to pull only the first commit from the pull request. Would you mind removing commit b897d63 from the request? then I'll be able to merge it. Thanks!

**Comment by jsdelfino** [comment]
I've added some comments to your commit. You can address them in this pull request if you want, or a subsequent one. Like I said, I will merge it (and Thanks for code!), just need you to discard the second 'merge into upstream' commit. Thanks!

**Comment by rajkiranrbala** [comment]
I will make the changes based on your suggestion

**Comment by rajkiranrbala** [comment]
I removed the commit b897d63.

**Comment by jsdelfino** [comment]
OK Thanks for removing the second commit. I've merged the pull request. Please open another one when you've addressed my review comments :) Thank you!

**Pull request merged**
