### PR TITLE
Add templates option in deploy-pipeline

### PR DESCRIPTION
**Pull request by astefanova**
Credentials should not be stored in abacus-config, they should be externalised. All credentials are now consumed from a single place (credentials file or exported environment variables).

### CODE REVIEW

**Comment by hsiliev** [comment]
Can you please squash your commits?

**Comment by astefanova** [comment]
Commits are now squashed.

**Comment by hsiliev** [comment]
Hey,

Thanks for the contribution. The change makes the configuration of Abacus easier and more secure so I want to have it as part of the Concourse pipeline.

We need some tests for the `replace-template` tool introduced in this PR.

**Comment by astefanova** [comment]
Tests are added with 
https://github.com/cloudfoundry-incubator/cf-abacus/pull/433/commits/5e30a66b7af0d201e39f1efb183d841af43b3bb0

**Comment by rajkiranrbala** [comment]
@astefanova 

Thank yo! 

@hsiliev 

I haven't used concourse before. Did you get a chance to test this?

**Comment by hsiliev** [comment]
Tested the pipeline with credentials file.

**Pull request merged**
